name: CI

# Define quando o fluxo vai ser disparado
on:
    push: 
        branches: ["main"]
        tags: ['v*.*.*']
    pull_request:
        branches: ["main"]
env:
    REGISTRY: docker.io
    DOCKER_USERNAME: cristiantebaldi
    IMAGE_NAME: cristiantebaldi/docker-prod-test
    SHA: ${{ github.event.pull_request.head.sha || github.event.after}} # Isso aqui serve para o id do commit do PR ou pegar o id do commit do push.

jobs:
    ci:
        runs-on: ubuntu-latest # Os jobs precisarm rodar dentro de um ambiente, nesse caso, o ubuntu-latest

        permissions:
            contents: read # Ler o conteúdo do repositório
            packages: write # Permitir publicar pacotes no GitHub Packages
            pull-requests: write # Permitir criar e atualizar pull requests
            security-events: write # Enviar eventos de segurança para o GitHub Security

        steps:
            # O actions/checkout@v6 vai fazer um git checkout do código do repositório que seria o branch main ou a tag v*.*.*
            - name: Checkout repository 
              uses: actions/checkout@v6
            
            # Vai instalar o Docker + A configuração do Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4 
            
            # Fazer o login para conseguir fazer o push da imagem e executar o docker scout
            - name: Login into registry ${{env.REGISTRY}}
              uses: docker/login-action@v4
              with:
                registry: ${{env.REGISTRY}}
                username: ${{env.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}

            - name: Build for CI
              id: build-id # O id não é obrigatório, mas ele é útil para referenciar o resultado dessa etapa em etapas posteriores
              uses: docker/build-push-action@v7 # Essa ação basicamente faz um "docker buildx build ."
              with:
                context: ./nestjs-project
                file: ./nestjs-project/Dockerfile.prod
                push: false # Eu quero apenas construir a imagem, não quero fazer o push ainda
                load: true # Como o docker buildx build utiliza o driver do docker-container, eu preciso utilizar o load para a imagem ficar disponível para o docker engine
                target: ci # O target é a etapa do Dockerfile que eu quero construir, nesse caso, a etapa "ci"
                # Utiliza o cache do GitHub Actions para armazenar as camadas da imagem
                cache-from: type=gha # O cache-from vai utilizar o cache criado na máquina do GitHub Actions, é claro que é limitado pois estou utilzando a infraestrutura do GitHub, e em algum momento será necessário pagar  
                cache-to: type=gha,mode=max # O mode=max vai tentar armazenar o máximo possível de camadas no cache, ou seja, as outras etapas do Dockerfile também serão cacheadas.
                tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:ci
                secrets: |
                  github_token=${{secrets.MY_GITHUB_TOKEN}}
            - name: Up Containers
              run: |
                docker compose -f ./nestjs-project/compose.ci.yaml up -d --wait-timeout 10 
            - name: Run tests
              run: echo "running tests..."
            - name: Build for Analysis
              id: build-analysis
              uses: docker/build-push-action@v7
              with:
                context: ./nestjs-project
                file: ./nestjs-project/Dockerfile.prod
                push: false
                load: true
                tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.SHA}}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                secrets: |
                  github_token=${{secrets.MY_GITHUB_TOKEN}}
            - name: Analyze for critical and high vulnerabilities
              id: docker-scout-cves
              uses: docker/scout-action@v1.20.4
              with:
                command: cves
                image: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.SHA}}
                # Vai mostrar todas as CVEs que são criticas ou altas que tem correção disponível.
                only-severities: critical,high
                only-fixed: true
                summary: true
                exit-code: true # Vai travar o CI caso seja encontrado alguma vulnerabilidade crítica ou alta com correção disponível

            - name: Analyze for all CVEs
              id: docker-scout-all-cves
              uses: docker/scout-action@v1.20.4
              with:
                command: cves
                image: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.SHA}}
                summary: true
                sarif-file: sarif.output.json
            - name: Upload SARIF result
              id: upload-sarif
              if: ${{ github.event_name != 'pull_request' }} # O upload do SARIF só vai ser feito para os eventos de push, para não poluir a aba de segurança do GitHub com análises de PRs
              uses: github/codeql-action/upload-sarif@v4
              with:
                sarif_file: sarif.output.json